APPLICATION = driver_srf04

BOARD ?= calliope-mini

RIOTBASE ?= $(CURDIR)/../..

FEATURES_REQUIRED = periph_gpio

USEMODULE += srf04
USEMODULE += xtimer
USEMODULE += shell

include $(RIOTBASE)/Makefile.include
