include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := i-nucleo-lrwan1

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += gnrc
USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += netstats_l2

include $(RIOTBASE)/Makefile.include
