include ../Makefile.tests_common

USEPKG += nanopb

# CI doesn't have the generator plugin installed,
# so disable CI testing for now.
#TEST_ON_CI_WHITELIST += all

include $(RIOTBASE)/Makefile.include
