# define the cpu used by the udoo board
export CPU = sam3
export CPU_MODEL = sam3x8e

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# setup the flash tool (BOSSA)
export BOSSA_ARDUINO_PREFLASH = yes
include $(RIOTMAKE)/tools/bossa.inc.mk
