# we use shared STM32 configuration snippets
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

DEBUG_ADAPTER ?= stlink
STLINK_VERSION ?= 2-1

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
