STM32_VARIANT = $(call uppercase,$(CPU_FAM))

CFLAGS += -D__SYSTEM_STM32$(STM32_VARIANT)XX_H
INCLUDES += -I$(RIOTBASE)/pkg/stm32cube/cache/$(CPU_FAM)/Drivers/CMSIS/Device/ST/STM32$(STM32_VARIANT)xx/Include
