RIOTBASE ?= $(CURDIR)/../../..
include $(RIOTBASE)/tests/Makefile.tests_common

FEATURES_REQUIRED += cpp libstdcpp

USEMODULE += module
EXTERNAL_MODULE_DIRS += $(CURDIR)/module

include $(RIOTBASE)/Makefile.include
