ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += lis2dh12_spi
  # TODO: enable drivers once their adaption/implementations are merged
  # USEMODULE += bme280_spi
endif

# STDIO on this board is available via Segger's RTT
USEMODULE += stdio_rtt

include $(RIOTBOARD)/common/nrf52/Makefile.dep
