ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += bme280_spi
  USEMODULE += lis2dh12_spi
endif

ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += nrfmin
endif

include $(RIOTBOARD)/common/nrf52/Makefile.dep
