ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += lis2dh12_spi
  # TODO: enable drivers once their adaption/implementations are merged
  # USEMODULE += bme280_spi
endif

# Use Segger's RTT by default for stdio on this board
DEFAULT_MODULE += stdio_rtt

include $(RIOTBOARD)/common/nrf52/Makefile.dep
