# for this board, we are using Segger's RTT as default terminal interface
TERMPROG = $(RIOTTOOLS)/jlink/jlink.sh
TERMFLAGS = term-rtt

# use shared Makefile.include
include $(RIOTBOARD)/common/nrf52xxxdk/Makefile.include
