# define the cpu used by the stm32f4-discovery board
export CPU = stm32f4
export CPU_MODEL = stm32f407vg

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

export ROM_SIZE = 0x100000
export RAM_SIZE = 0x20000
export CCMRAM_SIZE = 0x10000

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
