CPU = ezr32wg
CPU_MODEL = ezr32wg330f256r60

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart

# The board MCU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = cortex_m4_1
