RIOTBASE ?= $(CURDIR)/../../..
include $(RIOTBASE)/tests/Makefile.tests_common

USEMODULE += embunit

USEMODULE += vfs
USEMODULE += devfs
USEMODULE += devfs_random
USEMODULE += devfs_hwrng

include $(RIOTBASE)/Makefile.include
