APPLICATION = openwsn_cryptoengine
include ../Makefile.tests_common

USEPKG += openwsn

USEMODULE += openwsn_ledpins
USEMODULE += openwsn_sctimer
USEMODULE += openwsn_cryptoengine

include $(RIOTBASE)/Makefile.include
