# define the cpu used by the nucleo144-f303 board
export CPU = stm32f3
export CPU_MODEL = stm32f303ze

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x80000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x10000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ccmram_len=0x4000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1ffff7ac

# load the common Makefile.include for Nucleo-144 boards
include $(RIOTBOARD)/nucleo144-common/Makefile.include
