MODULE=esp_idf_esp32

include $(RIOTBASE)/Makefile.base

INCLUDES += -I$(RIOTCPU)/$(CPU)/esp-idf/include/esp32
INCLUDES += -I$(RIOTCPU)/$(CPU)/esp-idf/include/log
INCLUDES += -I$(SDK_DIR)/components/esp32
INCLUDES += -I$(SDK_DIR)/components/nvs_flash/include
