MODULE=esp_idf_esp32

include $(RIOTBASE)/Makefile.base

INCLUDES += -I$(RIOTCPU)/$(CPU)/esp-idf/include/esp32
INCLUDES += -I$(RIOTCPU)/$(CPU)/esp-idf/include/log
INCLUDES += -I$(RIOTCPU)/$(CPU)/esp-idf/wpa_supplicant/port/include
INCLUDES += -I$(SDK_DIR)/components/esp32
INCLUDES += -I$(SDK_DIR)/components/esp32/include
INCLUDES += -I$(SDK_DIR)/components/nvs_flash/include
INCLUDES += -I$(SDK_DIR)/components/soc/esp32/include
INCLUDES += -I$(SDK_DIR)/components/smartconfig_ack/include
INCLUDES += -I$(SDK_DIR)/components/wpa_supplicant/include
INCLUDES += -I$(SDK_DIR)/components/wpa_supplicant/include/crypto
INCLUDES += -I$(SDK_DIR)/components/wpa_supplicant/port/include
