# include optional dependencies
include $(RIOTBOARD)/common/arduino-atmega/Makefile.dep

INCLUDES += -I$(RIOTBOARD)/common/arduino-atmega/include

include $(RIOTMAKE)/tools/serial.inc.mk

# include flashing tool
include $(RIOTMAKE)/tools/avrdude.inc.mk
