# Inherit common ATmega features
include $(RIOTBOARD)/common/atmega/Makefile.features

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += arduino
FEATURES_PROVIDED += periph_pwm
