USEMODULE += iotlab-common

# export ROM partitions
export ROM_SIZE = 0x80000
export SLOT0_ADDR = 0x8000000
export SLOT0_SIZE = 0x4000
CFLAGS +=-DSLOT0_SIZE=$(SLOT0_SIZE)
export SLOT_SIZE = 0x3E000
CFLAGS +=-DSLOT_SIZE=$(SLOT_SIZE)
export SLOT1_SIZE = 0x3E000
CFLAGS +=-DSLOT1_SIZE=$(SLOT1_SIZE)
export SLOT2_SIZE = 0x3E000
CFLAGS +=-DSLOT2_SIZE=$(SLOT2_SIZE)

include $(RIOTBOARD)/iotlab-common/Makefile.include

# add iotlab-m3 include path
INCLUDES += -I$(RIOTBOARD)/$(BOARD)/include
