# Define the module that is built:
MODULE = cpu

EXCLUDE += esp-idf
EXCLUDE += periph
EXCLUDE += xtensa

# Add a list of subdirectories, that should also be built:
DIRS += esp-idf
DIRS += periph
DIRS += xtensa

include $(RIOTBASE)/Makefile.base
