RIOTBASE ?= $(CURDIR)/../../..
include $(RIOTBASE)/tests/Makefile.tests_common

USEMODULE += embunit
USEMODULE += fmt
USEPKG += tinycbor

USEMODULE += tinycbor_float

include $(RIOTBASE)/Makefile.include
