# configure the serial terminal
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))
include $(RIOTMAKE)/tools/serial.inc.mk

# Default is to use ST-link v2-1 adapter (used by all Nucleos)
export DEBUG_ADAPTER ?= stlink
export STLINK_VERSION ?= 2-1

# Include openocd adapters for st-link
include $(RIOTMAKE)/tools/openocd-adapters/stlink.inc.mk

# Include openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
