"Area: arduino API":
  - sys/arduino/**/*

"Area: BLE":
  - pkg/nimble/**/*
  - sys/net/**/*
  - sys/include/net/**/*

"Area: boards":
  - boards/**/*

"Area: build system":
  - Makefile.*
  - makefiles/**/*
  - ./**/*.mk

"Area: CI":
  - .circleci/**/*
  - .github/**/*.yml
  - .murdock

"Area: CoAP":
  - sys/net/application_layer/*coap/**/*
  - sys/net/include/*coap*/**/*

"Area: core":
  - core/**/*

"Area: cpu":
  - cpu/**/*

"Area: doc":
  - ./**/*.txt
  - doc/**/*
  - ./*.md

"Area: drivers":
  - drivers/**/*

"Area: examples":
  - examples/**/*

"Area: Kconfig":
  - dist/tools/kconfiglib/**/*
  - makefiles/kconfig.mk
  - kconfigs/*
  - Kconfig

"Area: network":
  - sys/net/**/*
  - sys/include/net/**/*
  - pkg/lwip/**/*
  - pkg/openthread/**/*
  - pkg/openwsn/**/*
  - pkg/paho-mqtt/**/*

"Area: OTA":
  - sys/suit/**/*
  - sys/include/suit/**/*
  - sys/include/suit.h

"Area: pkg":
  - pkg/**/*

"Area: SAUL":
  - drivers/saul/**/*
  - drivers/include/saul/**/*
  - drivers/include/saul.h
  - sys/saul_reg/**/*
  - sys/include/saul_reg.h

"Area: sys":
  - sys/**/*

"Area: tests":
  - tests/**/*
  - fuzzing/**/*
  - dist/pythonlibs/**/*
  - makefiles/tests/**/*

"Area: timers":
  - sys/*timer/**/*
  - sys/include/*timer/**/*
  - sys/include/*timer.h

"Area: toolchain":
  - makefiles/toolchain/**/*

"Area: tools":
  - dist/tools/**/*
  - dist/testbed-support/**/*
  - makefiles/tools/**/*

"Area: USB":
  - sys/usb/**/*
  - sys/include/usb/**/*
  - sys/include/usb.h
