# tell the build system that the CPU depends on the atmega common files
USEMODULE += atmega_common

# CPU depends on the atmega common module, so include it
include $(RIOTCPU)/atmega_common/Makefile.include
