# tell the build system that the CPU depends on the atmega common files
USEMODULE += atmega_common

RAM_LEN = 8K
ROM_LEN = 256K

# atmega2560 additionally has PCINT2
ifneq (,$(filter atmega_pcint,$(USEMODULE)))
  USEMODULE += atmega_pcint2
endif

# CPU depends on the atmega common module, so include it
include $(RIOTCPU)/atmega_common/Makefile.include
