kind: pipeline
type: docker
name: static_tests

environment:
  CLICOLOR_FORCE: 1
  NPROC_MAX: 4
  GIT_CACHE_DIR: /cache/git

clone:
  disable: true

steps:
  - name: clone
    image: kaspar030/drone-clone
    settings:
      SSH_KEY:
        from_secret: ssh_key
      base_repo: ${DRONE_REPO_LINK}
      base_branch: ${DRONE_REPO_BRANCH}
      build_repo: ${DRONE_GIT_HTTP_URL}
      build_branch: ${DRONE_SOURCE_BRANCH}
      build_commit: ${CI_COMMIT_SHA}
      merge_commit_repo: "riot-ci/RIOT"

  - name: build
    image: riot/riotbuild:latest
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
    - test -n "$${DRONE_PULL_REQUEST}"
    - export MERGE_COMMIT="$$(cat merge_commit)"
    - git-cache clone https://github.com/riot-ci/RIOT $${MERGE_COMMIT} build
