kind: pipeline
type: docker
name: build
trigger:
  event:
    - pull_request

environment:
  DRONE_CLONE_REPO: riot-ci/RIOT
  CLICOLOR_FORCE: 1
  NPROC_MAX: 4
  GIT_CACHE_DIR: /cache/git

clone:
  disable: true

services:
  # this service launches a container running an autossh session that
  # connects to murdock-slave@ci.riot-os.org, creating port forwards to the
  # disque and redis instances there. It will be automatically killed at the end
  # of this pipeline.
  - name: disque
    image: kaspar030/autossh
    settings:
      ssh_key:
        from_secret: ssh_key_murdock
      user: murdock-slave
      host: ci.riot-os.org
      ssh_args: "-L0.0.0.0:7711:localhost:7711 -L0.0.0.0:6379:localhost:6379"
    ports: [ 6379, 7711 ]

steps:
  # As we're building distributed, we need to make sure that every worker is using the exact same commit.
  # We also want to test the PR branch *merged into current master*.
  # This step creates that merge commit and pushes it to riot-ci/RIOT.
  # The resulting commit hash will be stored in "merge_commit" in the working
  # directory (which is shared with the subsequent steps by drone via a docker
  # volume).
  - name: clone
    image: kaspar030/drone-clone
    settings:
      SSH_KEY:
        from_secret: ssh_key_clone
      mode: clone
      base_repo: ${DRONE_REPO_LINK}
      base_branch: ${DRONE_REPO_BRANCH}
      build_repo: ${DRONE_GIT_HTTP_URL}
      build_branch: ${DRONE_SOURCE_BRANCH}
      build_commit: ${CI_COMMIT_SHA}
      merge_commit_repo: riot-ci/RIOT

  # This build step launches the distributed build.
  - name: build
    image: kaspar030/drone-dwq
    commands:

    # setting disque parameters
    - export DWQ_DISQUE_URL="disque:7711"
    - export DWQ_COMMIT="$$(cat merge_commit)"
    - export DWQ_REPO="https://github.com/$${DRONE_CLONE_REPO}"

    # running trivial "true" on default queue
    - dwqc -q drone-breeze "true"

    # ensuring redis is operational
    - redis-cli -h disque ping

    # launch the actual build
    #- >
    #  dwqc -E APPS=examples/hello-world -E BOARDS=native './.murdock get_jobs'
    #  | dwqc --quiet -P --outfile result.json

    - dwqc -q drone-breeze hostname
    - dwqm control --shutdown drone-breeze

---
kind: pipeline
type: docker
name: dwq-worker-breeze
trigger:
  event:
    - pull_request

environment:
  DRONE_CLONE_REPO: riot-ci/RIOT
  CLICOLOR_FORCE: 1
  NPROC_MAX: 4
  GIT_CACHE_DIR: /cache/git

clone:
  disable: true

services:
  # this service launches a container running an autossh session that
  # connects to murdock-slave@ci.riot-os.org, creating port forwards to the
  # disque and redis instances there. It will be automatically killed at the end
  # of this pipeline.
  - name: disque
    image: kaspar030/autossh
    settings:
      ssh_key:
        from_secret: ssh_key_murdock
      user: murdock-slave
      host: ci.riot-os.org
      ssh_args: "-L0.0.0.0:7711:localhost:7711 -L0.0.0.0:6379:localhost:6379"
    ports: [ 6379, 7711 ]

steps:
  # This build step launches the distributed build.
  - name: build
    image: kaspar030/riotdocker:latest
    environment:
      CCACHE: ccache
      CCACHE_DIR: /cache/ccache
    commands:
    # setting disque parameters
    - export DWQ_DISQUE_URL="disque:7711"
    - mkdir -p $${CCACHE_DIR}
    - git-cache init
    - pip3 install --upgrade dwq
    - dwqw --name drone-breeze --jobs 16 --queues drone-breeze

