kind: pipeline
type: docker
name: static_tests

environment:
  DRONE_CLONE_REPO: riot-ci/RIOT
  CLICOLOR_FORCE: 1
  NPROC_MAX: 4
  GIT_CACHE_DIR: /cache/git

clone:
  disable: true

services:
  - name: disque
    image: kaspar030/autossh
    environment:
      SSH_KEY:
        from_secret: ssh_key
    ports: [ 6379, 7711 ]
    commands:
      - mkdir /root/.ssh
      - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H ci.riot-os.org >> /etc/ssh/ssh_known_hosts 2> /dev/null
      - exec autossh -M 0 -C -N -L7711:0.0.0.0:7711 -L6379:0.0.0.0:6379 -o ServerAliveInterval=60 -o ServerAliveCountMax=2 murdock-slave@ci.riot-os.org

steps:
  - name: clone
    image: kaspar030/drone-clone
    settings:
      SSH_KEY:
        from_secret: ssh_key
      mode: clone
      base_repo: ${DRONE_REPO_LINK}
      base_branch: ${DRONE_REPO_BRANCH}
      build_repo: ${DRONE_GIT_HTTP_URL}
      build_branch: ${DRONE_SOURCE_BRANCH}
      build_commit: ${CI_COMMIT_SHA}
      merge_commit_repo: riot-ci/RIOT

  - name: build
    image: riot/riotbuild:latest
    commands:
    - test -n "$${DRONE_PULL_REQUEST}"

    - export DWQ_COMMIT="$$(cat merge_commit)"
    - export DWQ_REPO="https://github.com/$${DRONE_CLONE_REPO}"
    - dwqc "echo foo"
    - redis-cli -h disque ping
