# Process FEATURES variables
#
# The board/board common are responsible for defining the CPU and CPU_MODEL
# variables in their Makefile.features.
# This makes them available when setting features based on CPU_MODEL in the cpu
# Makefile.features and also during dependency resolution.

# Transition:
#   Moving 'CPU/CPU_MODEL' to Makefile.features is an ongoing work and may not
#   reflect the state of all boards for the moment.

include $(RIOTBOARD)/$(BOARD)/Makefile.features
