include ../Makefile.tests_common

USEMODULE += sens0_i2c
USEMODULE += saul_reg

# For xtimer_periodic_wakeup
USEMODULE += xtimer
# For phydat_dump
USEMODULE += phydat

include $(RIOTBASE)/Makefile.include
