ifneq (,$(filter eepreg,$(USEMODULE)))
  FEATURES_REQUIRED += periph_eeprom
endif

ifneq (,$(filter json,$(USEMODULE)))
  USEMODULE += fmt
endif

ifneq (,$(filter prng_fortuna,$(USEMODULE)))
  CFLAGS += -DCRYPTO_AES
endif
