BOARD_INSUFFICIENT_MEMORY := \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-l031k6 \
    stm32f030f4-demo \
    #

BOARD_BLACKLIST := \
    mega-xplained # conflict between RTC and RTT features \
    #
