# define the cpu used by SAMR21 Xplained Pro board
export CPU = samd21
export CPU_MODEL = samr21g18a

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x40000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x8000

# set edbg device type
EDBG_DEVICE_TYPE = atmel_cm0p

include $(RIOTMAKE)/boards/sam0.inc.mk
