# define the used CPU model
export CPU_MODEL = nrf51x22xxaa

# include common nrf51 boards module into the build
USEMODULE += boards_common_nrf51

# this board uses an ST-Link v2 debug adapter
DEBUG_ADAPTER ?= stlink
STLINK_VERSION ?= 2

PROGRAMMER = openocd

# import nrf51 common openocd configuration
include $(RIOTBOARD)/common/nrf51/Makefile.include
