# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))
# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# setup flash tool
export FLASHER = $(RIOTTOOLS)/goodfet/goodfet.bsl
export FFLAGS = --z1 -I -c $(PORT) -r -e -p $(HEXFILE)
