ifeq (native,$(BOARD))
  USEMODULE += netdev_tap
else
  USEMODULE += stdio_ethos
endif

USEMODULE += auto_init_gnrc_netif

# add dummy interface to test forwarding to smaller MTU
USEMODULE += netdev_test

# Specify the mandatory networking modules for IPv6
USEMODULE += gnrc_ipv6_router_default
USEMODULE += gnrc_icmpv6_error
USEMODULE += gnrc_pktdump
USEMODULE += gnrc_pktbuf_cmd

# IPv6 extension headers
USEMODULE += gnrc_ipv6_ext_frag

# UDP support for payload
USEMODULE += gnrc_udp
USEMODULE += od

# Add unittest framework
USEMODULE += embunit

# Add also the shell, some shell commands
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
