# define the cpu used by the arduino due board
export CPU = sam3
export CPU_MODEL = sam3x8e

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# setup flasher (using BOSSA)
export BOSSA_ARDUINO_PREFLASH = yes
include $(RIOTMAKE)/tools/bossa.inc.mk
