RIOTBASE ?= $(CURDIR)/../../..
include $(RIOTBASE)/tests/Makefile.tests_common

USEMODULE += xtimer
USEMODULE += shell

#for testing
#USEMODULE += ps
#USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include
