# define the cpu used by the nucleo144-f446 board
export CPU = stm32f4
export CPU_MODEL = stm32f446ze

export ROM_SIZE = 0x80000
export RAM_SIZE = 0x20000

# load the common Makefile.include for Nucleo-144 boards
include $(RIOTBOARD)/nucleo144-common/Makefile.include
