# define the cpu used by the nucleo144-f446 board
export CPU = stm32f4
export CPU_MODEL = stm32f446ze

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x80000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x20000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1fff7a10

# load the common Makefile.include for Nucleo-144 boards
include $(RIOTBOARD)/nucleo144-common/Makefile.include
