BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-mega2560 \
    arduino-uno \
    atmega1284p \
    atmega328p \
    atmega128rfa1 \
    i-nucleo-lrwan1 \
    mega-xplained \
    microduino-corerf \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-l031k6 \
    nucleo-l053r8 \
    stm32f030f4-demo \
    stm32f0discovery \
    stm32l0538-disco \
    waspmote-pro
    #
