ifneq (,$(filter periph_rtc,$(USEMODULE)))
  USEMODULE += rtt_rtc
endif

# include nrf5x common periph drivers
USEMODULE += nrf5x_common_periph

# link common cpu code
USEMODULE += cpu_common

ifneq (,$(filter nrfmin,$(USEMODULE)))
  FEATURES_REQUIRED += radio_nrfmin
  FEATURES_REQUIRED += periph_cpuid
  USEMODULE += netif
endif
