INCLUDES += -I$(PKGDIRBASE)/flatbuffers/include

FLATC ?= flatc

ifneq (0,$(shell which flatc 2>&1 > /dev/null ; echo $$?))
  FLATC = $(RIOTTOOLS)/flatc/flatc
  $(call target-export-variables,all,$(FLATC))
  BUILDDEPS += $(FLATC)
endif

CXXEXFLAGS += -Wno-type-limits
