# This board is based on an ATmega CPU, thus import the features from it
include $(RIOTBOARD)/common/atmega/Makefile.features

# Various other features (if any)

-include $(RIOTCPU)/atmega1284p/Makefile.features
