# Include shared STM32 headers
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# custom flasher to use with the bootloader
FLASHER = $(RIOTBOARD)/opencm904/dist/robotis-loader.py
DEBUGGER =
DEBUGSERVER =

FLASHFILE ?= $(BINFILE)
FFLAGS = $(PROG_DEV) $(FLASHFILE)
DEBUGGER_FLAGS =

# Skip the space needed by the embedded bootloader
ROM_OFFSET ?= 0x3000
