export MEMORY_BASE=0x80000000
export MEMORY_SIZE=1M
export APP_START=0x80000000

include $(RIOTMAKE)/arch/mips.inc.mk

export USEMODULE += periph
export USEMODULE += newlib

#To use UHI to handle syscall (default)
export LINKFLAGS += -luhi -Tuhi32.ld
export USEMODULE += newlib_syscalls_mips_uhi

#To Use RIOT to handle syscalls (VFS)
#export LINKFLAGS += -Tuhi32.ld
#export USEMODULE += vfs
#export USEMODULE += newlib_syscalls_default
