INCLUDES += -I$(RIOTCPU)/mips32r2_common/include

ifeq ($(USE_UHI_SYSCALLS),1)
  #Use UHI to handle syscalls
  LINKFLAGS += -luhi
  USEMODULE += newlib_syscalls_mips_uhi
  CFLAGS += -DHAVE_HEAP_STATS
endif
