ifneq (,$(filter periph_rtc,$(USEMODULE)))
  USEMODULE += periph_rtt
endif
ifneq (,$(filter periph_timer,$(USEMODULE)))
  # RTT is used as the time base for the LPTMR driver.
  # TODO: Remove when LPTMR is refactored.
  USEMODULE += periph_rtt
endif
