PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# Bossa is the default programmer
PROGRAMMER ?= bossa

# Include all definitions for flashing with bossa other USB
include $(RIOTBOARD)/common/samd21-arduino-bootloader/Makefile.include

# setup the boards dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep
