APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))
APPLICATION_DIR ?= $(notdir $(patsubst %/,%,$(dir $(lastword $(CURDIR)))))

ifneq (,$(wildcard $(CURDIR)/tests/.))
  DEFAULT_MODULE += test_utils_interactive_sync
endif

ifneq (,$(filter drivers,$(APPLICATION_DIR)))
  BOARD ?= samr21-xpro
endif
BOARD ?= native
RIOTBASE ?= $(CURDIR)/../..
QUIET ?= 1
# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1
