USEMODULE += lvgl_core
USEMODULE += lvgl_draw
USEMODULE += lvgl_font
USEMODULE += lvgl_hal
USEMODULE += lvgl_misc
USEMODULE += lvgl_objx
USEMODULE += lvgl_themes

USEMODULE += lvgl_contrib
USEMODULE += disp_dev
USEMODULE += xtimer
