# Put the package dependencies here

USEMODULE += fmt
USEMODULE += driver_llcc68_hal
USEMODULE += ztimer_usec
USEMODULE += ztimer_msec

# If RTT feature is available use the RTT backend of ztimer
FEATURES_OPTIONAL += periph_rtt
ifneq (,$(filter periph_rtt,$(FEATURES_USED)))
  USEMODULE += ztimer_periph_rtt
endif

# required features
FEATURES_REQUIRED += periph_spi
