BOARD_INSUFFICIENT_MEMORY := \
    6lowpan-clicker \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega328p \
    chronos \
    msb-430 \
    msb-430h \
    nucleo-f031k6 \
    nucleo-f042k6 \
    pic32-wifire \
    stm32f030f4-demo \
    #
