ifneq (,$(filter arch_arm_cortex_m,$(FEATURES_USED)))
  USEMODULE += qDSA_asm
endif

ifneq (,$(filter arch_avr8,$(FEATURES_USED)))
  USEMODULE += qDSA_asm
endif

# qDsa is not 16 bit compatible
FEATURES_BLACKLIST += arch_16bit
