PKG_NAME=qdsa
PKG_URL=https://github.com/MrKevinWeiss/qdsa.git
PKG_VERSION=dc77a70015e2a1e0403fd2c4935295e75f66daa8
PKG_LICENSE=PD

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)/$(QDSA_IMPL)
