# This board is based on an atmega CPU, thus import the features from it
include $(RIOTCPU)/atmega_common/Makefile.features

# Various other features (if any)

-include $(RIOTCPU)/atmega1281/Makefile.features
