INCLUDES += -I$(PKGDIRBASE)/mbedtls/include
INCLUDES += -I$(PKGDIRBASE)/mbedtls/include/mbedtls

INCLUDES += -I$(RIOTPKG)/mbedtls/include

CFLAGS += -DMBEDTLS_CONFIG_FILE='<riot_config.h>'

DIRS += $(RIOTPKG)/mbedtls/contrib

PSEUDOMODULES += mbedtls_entropy_source_hwrng
PSEUDOMODULES += mbedtls_entropy_source_adc
