INCLUDES += -I$(PKGDIRBASE)/libcose/include
CFLAGS += -DUSE_CBOR_CONTEXT

ifneq (,$(filter libcose_crypt_tweetnacl,$(USEMODULE)))
  CFLAGS += -DCRYPTO_TWEETNACL
endif
ifneq (,$(filter libcose_crypt_hacl,$(USEMODULE)))
  CFLAGS += -DCRYPTO_HACL
endif

# Declare pseudomodules here to be selfcontained
PSEUDOMODULES += libcose_crypt_%

# There is a problem with the LLVM assembler and the assembly part of this
# package
TOOLCHAINS_BLACKLIST += llvm
