MODULE=esp_idf_eth_phy

include $(RIOTBASE)/Makefile.base

INCLUDES += -I$(RIOTCPU)/$(CPU)/esp-idf/include/esp32
INCLUDES += -I$(RIOTCPU)/$(CPU)/esp-idf/include/log
INCLUDES += -I$(SDK_DIR)/components/ethernet/include
