include ../Makefile.tests_common

USEMODULE += posix_time

# This application uses getchar and thus except input from stdio
USEMODULE += stdio_uart_rx

TEST_ON_CI_WHITELIST += all

include $(RIOTBASE)/Makefile.include
