include ../Makefile.tests_common

USEMODULE += posix_time

# This application uses getchar and thus expect input from stdio
USEMODULE += stdio_rx

TEST_ON_CI_WHITELIST += all

include $(RIOTBASE)/Makefile.include
