ifneq (,$(filter nrf802154,$(USEMODULE)))
  FEATURES_REQUIRED += periph_timer
  FEATURES_REQUIRED += radio_nrf802154
  USEMODULE += luid
  USEMODULE += netdev_ieee802154
endif

ifneq (,$(filter periph_spi,$(FEATURES_REQUIRED)))
  FEATURES_REQUIRED += periph_gpio_irq
endif

include $(RIOTCPU)/nrf5x_common/Makefile.dep
include $(RIOTCPU)/cortexm_common/Makefile.dep
