export CPU_ARCH = cortex-m4f
export CPU_FAM  = nrf52

# Export internal ROM alignment and image header size for bootloader support
export IMAGE_ALIGN = 8
export IMAGE_HDR_SIZE = 512

include $(RIOTCPU)/nrf5x_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
