ifeq (FreeBSD,$(OS))
  ifneq ($(DISABLE_LIBSTDCPP),1)
    # static C++ constructors need guards for thread safe initialization
    ifneq (,$(filter cpp,$(FEATURES_USED)))
      USEMODULE += cxx_ctor_guards
    endif
  endif
endif

ifneq (,$(filter periph_spi,$(USEMODULE)))
  USEMODULE += periph_spidev_linux
endif
ifeq (,$(filter stdio_%,$(USEMODULE)))
  USEMODULE += stdio_native
endif

USEMODULE += periph

# UART is needed by startup.c
USEMODULE += periph_uart
