ifeq ($(OS),Linux)
  ifneq (,$(filter periph_gpio,$(USEMODULE)))
    DEFAULT_MODULE += periph_gpio_linux
  endif
  ifneq (,$(filter periph_spi,$(USEMODULE)))
    DEFAULT_MODULE += periph_spidev_linux
  endif
endif

ifeq (,$(filter stdio_%,$(USEMODULE)))
  USEMODULE += stdio_native
endif

USEMODULE += periph

# UART is needed by startup.c
USEMODULE += periph_uart
