FEATURES_PROVIDED += arch_32bit
FEATURES_PROVIDED += arch_native
FEATURES_PROVIDED += cpp
FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_hwrng
FEATURES_PROVIDED += periph_pm
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += ssp

ifeq ($(OS),Linux)
  # Access to hardware SPI bus is only supported on Linux hosts
  FEATURES_PROVIDED += periph_spi
  # Hardware GPIO access is only available on Linux hosts
  FEATURES_PROVIDED += periph_gpio periph_gpio_irq
endif
