include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno

FEATURES_REQUIRED = periph_i2c

USEMODULE += at30tse75x
USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include
