APPLICATION = driver_at30tse75x
include ../Makefile.tests_common

FEATURES_REQUIRED = periph_i2c

USEMODULE += at30tse75x
USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include
