ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += lis2dh12
  USEMODULE += hts221
  USEMODULE += lps22hb
endif

# STDIO on this board is available via Segger's RTT
FEATURES_REQUIRED += stdio_rtt

include $(RIOTBOARD)/common/nrf52/Makefile.dep
