# Configure Segger's RTT when stdio_rtt is loaded
ifneq (,$(filter stdio_rtt,$(USEMODULE)))
  TERMPROG = $(RIOTTOOLS)/jlink/jlink.sh
  TERMFLAGS = term-rtt
endif

# use shared Makefile.include
include $(RIOTBOARD)/common/nrf52/Makefile.include
