ifeq (native,$(BOARD))
  USEMODULE += netdev_tap
else
  USEMODULE += stdio_ethos
endif

USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_ipv6_default
USEMODULE += gnrc_tcp
USEMODULE += gnrc_pktbuf_cmd
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += od
