export CPU = mips_pic32mz
export CPU_MODEL=p32mz2048efg100
export APPDEPS += $(RIOTCPU)/$(CPU)/$(CPU_MODEL)/$(CPU_MODEL).S
export USE_UHI_SYSCALLS = 1

FLASHFILE ?= $(HEXFILE)

ifeq ($(PROGRAMMER),jlink)
  export JLINK_DEVICE := PIC32MZ2048EFG100
  export JLINK_IF := JTAG
  include $(RIOTMAKE)/tools/jlink.inc.mk
endif
