MODULE = tensorflow-lite

SRCXXEXT = cc
SRCXXEXCLUDE := $(wildcard *_test.$(SRCXXEXT))

CXXEXFLAGS += -Wno-unused-parameter
CXXEXFLAGS += -Wno-unused-variable
CXXEXFLAGS += -Wno-type-limits
CXXEXFLAGS += -Wno-sign-compare
CXXEXFLAGS += -Wno-strict-aliasing

include $(RIOTBASE)/Makefile.base
