MODULE = tensorflow-lite-core

SRCXXEXT = cc
SRCXXEXCLUDE := $(wildcard *_test.$(SRCXXEXT))

NO_AUTO_SRC := 1
SRCXX := \
    error_reporter.cc \
    flatbuffer_conversions.cc \
    op_resolver.cc \
    tensor_utils.cc \
    #

CXXEXFLAGS += -Wno-sign-compare

include $(RIOTBASE)/Makefile.base
