FEATURES_REQUIRED += cpp
USEMODULE += cpp11-compat

USEPKG += flatbuffers
USEPKG += gemmlowp

USEMODULE += tensorflow-lite
USEMODULE += tensorflow-lite-c
USEMODULE += tensorflow-lite-core
USEMODULE += tensorflow-lite-kernels
USEMODULE += tensorflow-lite-kernels-internal
USEMODULE += tensorflow-lite-memory
USEMODULE += tensorflow-lite-micro-kernels

# Blacklist Cortex-M0 architecture because of too little stack size
ifneq (,$(filter cortex-m0%,$(CPU_ARCH)))
  FEATURES_BLACKLIST += arch_cortexm
endif
