MODULE = tensorflow-lite-kernels-internal

SRCXXEXT = cc

NO_AUTO_SRC := 1
SRCXX := quantization_util.cc

CXXEXFLAGS += -Wno-missing-field-initializers
CXXEXFLAGS += -Wno-unused-parameter
CXXEXFLAGS += -Wno-unused-function

include $(RIOTBASE)/Makefile.base
