MODULE = tensorflow-lite-c

NO_AUTO_SRC := 1
SRC := common.c

CFLAGS += -Wno-strict-prototypes
CFLAGS += -Wno-old-style-definition
CFLAGS += -DTF_LITE_STATIC_MEMORY

include $(RIOTBASE)/Makefile.base
