MODULE = tensorflow-lite-micro-kernels

SRCXXEXT = cc
SRCXXEXCLUDE := $(wildcard *_test.$(SRCXXEXT))

CXXEXFLAGS += -Wno-missing-field-initializers
CXXEXFLAGS += -Wno-unused-parameter

include $(RIOTBASE)/Makefile.base
