## the cpu to build for
export CPU = stm32l0
export CPU_MODEL = stm32l053r8

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x10000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x2000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1ff80050

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
