## the cpu to build for
export CPU = stm32f1
export CPU_MODEL = stm32f103cb

include $(RIOTBOARD)/common/blxxxpill/Makefile.include
export OPENOCD_CONFIG = $(RIOTBOARD)/common/blxxxpill/dist/openocd-128kib.cfg

USEMODULE += boards_common_blxxxpill
