BOARD ?= nucleo-f411re
include ../Makefile.tests_common

FEATURES_REQUIRED = cpu_stm32

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += bootloader_stm32

include $(RIOTBASE)/Makefile.include
