INCLUDES += -I$(RIOTBASE)/tests/unittests/bin/pkg/$(BOARD)/cryptoauthlib/test
INCLUDES += -I$(RIOTBASE)/pkg/cryptoauthlib_test/include

FEATURES_REQUIRED += periph_i2c
CFLAGS += -std=gnu11 -O3 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-int-conversion -Wno-unused-function -Wno-unused-variable 
CFLAGS += -DATCA_HAL_I2C -DDO_NOT_TEST_BASIC_UNIT -DDO_NOT_TEST_SW_CRYPTO
USEPKG += cryptoauthlib_test
USEMODULE += xtimer