# name of your application
APPLICATION = sha256

# If no BOARD is found in the environment, use this default:
BOARD ?= wsn430-v1_3b

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

# include sha256 (used by example blockwise handler)
USEMODULE += hashes

include $(RIOTBASE)/Makefile.include
