# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_uart

# Nordic SoftDevice support in RIOT is verified for this board
FEATURES_PROVIDED += ble_nordic_softdevice

include $(RIOTBOARD)/common/nrf52/Makefile.features
