USEMODULE += arm7_common
USEMODULE += bitfield
USEMODULE += periph
DEFAULT_MODULE += pm_layered

ifneq (,$(filter mci,$(USEMODULE)))
  USEMODULE += xtimer
endif

include $(RIOTCPU)/arm7_common/Makefile.dep
