# We must duplicate the include done by $(RIOTBASE)/Makefile.include
# to also include the main board header
INCLUDES += $(addprefix -I,$(wildcard $(RIOTBOARD)/nucleo-f103rb/include))

include $(RIOTBOARD)/nucleo-f103rb/Makefile.include
