# This must be a different name than 'board' as it is implemented by 'native'
USEMODULE += board_external_nucleo-f103rb

ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
  USEMODULE += at86rf233
endif

include $(RIOTBOARD)/nucleo-f103rb/Makefile.dep
