include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-leonardo arduino-nano \
                             arduino-uno nucleo-f031k6 stk3200

USEMODULE += shell
USEMODULE += at
USEMODULE += at_urc

include $(RIOTBASE)/Makefile.include
