## the cpu to build for
export CPU = msp430fxyz
export CPU_MODEL = msp430f1611

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# setup flash tool
export OFLAGS = -O ihex
export FLASHER = mspdebug
export FFLAGS = -d $(PORT) -j uif "prog $(HEXFILE)"

# include wsn430-common includes
export INCLUDES += -I$(RIOTBOARD)/wsn430-common/include
