# define the used CPU model
export CPU_MODEL ?= nrf51x22xxaa

# This board uses an ST-Link v2 debug adapter
export DEBUG_ADAPTER ?= stlink
export STLINK_VERSION ?= 2

# use openocd to program this board
PROGRAMMER = openocd

# import nrf51 boards common configuration
include $(RIOTBOARD)/common/nrf51/Makefile.include
