RIOTBASE ?= $(CURDIR)/../../..
include $(RIOTBASE)/tests/Makefile.tests_common

# This test should also work with Si1146 and Si1147 variants.
USEMODULE += si1145

include $(RIOTBASE)/Makefile.include
