# define the cpu used by the maple-mini board
export CPU = stm32f1
export CPU_MODEL = stm32f103cb

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

export ROM_SIZE = 0x20000
export RAM_SIZE = 0x5000

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
