# include module specific includes
INCLUDES += -I$(RIOTCPU)/atmega_common/include \
            -isystem$(RIOTCPU)/atmega_common/avr_libc_extra/include \
            -isystem$(RIOTCPU)/atmega_common/avr_libc_extra/include/vendor

include $(RIOTMAKE)/arch/atmega.inc.mk
