export CPU_ARCH = cortex-m3
export CPU_FAM  = stm32f1

USEMODULE += pm_layered

include $(RIOTCPU)/stm32_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk

ifneq (,$(filter stm32f103re,$(CPU_MODEL)))
  export ROM_SIZE = 0x80000
  export RAM_SIZE = 0x10000
else ifneq (,$(filter stm32f103rb stm32f103cb,$(CPU_MODEL)))
  export ROM_SIZE = 0x20000
  export RAM_SIZE = 0x5000
endif
