# define the cpu used by the stm32l0538-disco board
export CPU = stm32l0
export CPU_MODEL = stm32l053c8

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

export DEBUG_ADAPTER ?= stlink

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
