# We must duplicate the include done by $(RIOTBASE)/Makefile.include
# to also include the main board header
INCLUDES += $(addprefix -I,$(wildcard $(RIOTBOARD)/openmote-b/include))

include $(RIOTBOARD)/openmote-b/Makefile.include
