INCLUDES += -I$(RIOTPKG)/ccn-lite -I$(PKGDIRBASE)/ccn-lite/src
INCLUDES += -I$(RIOTBASE)/sys/posix/include

CFLAGS += -DCCNL_RIOT

EXTRA_LIBS += ${BINDIR}/ccn-lite.a
EXTRA_LIBS += ${BINDIR}/ccn-lite-utils.a
