# export this module and its includes
USEMODULE += boards_common_nucleo
INCLUDES  += -I$(RIOTBOARD)/common/nucleo/include

# nucleo boards use st-link
include $(RIOTBOARD)/common/stm32-stlink/Makefile.include
