APPLICATION = periph_pm
BOARD ?= slstk3401a
include ../Makefile.tests_common

FEATURES_REQUIRED += periph_pm

FEATURES_OPTIONAL += periph_rtc

USEMODULE += shell

include $(RIOTBASE)/Makefile.include
