## the cpu to build for
export CPU = stm32f1
export CPU_MODEL = stm32f103re

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB1
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbserial*)))

export ROM_SIZE = 0x80000
export RAM_SIZE = 0x10000

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
