INCLUDES += -I$(PKGDIRBASE)/jerryscript/jerry-core/include
INCLUDES += -I$(PKGDIRBASE)/jerryscript/jerry-ext/include

# There are problem with unused `-mcpu...` arguments in clang and with
# ranlib + LLVM/clang in this package
TOOLCHAINS_BLACKLIST += llvm
