INCLUDES += -I$(PKGDIRBASE)/jerryscript/jerry-core/include
INCLUDES += -I$(PKGDIRBASE)/jerryscript/jerry-ext/include

# the jerryscript build produces static archives
USEARCHIVE += \
  jerryscript \
  jerryscript-ext \
  jerryport-minimal \
#
