PSEUDOMODULES += esp32_wrover_kit_camera

USEMODULE += boards_common_esp32
USEMODULE += esp_rtc_timer_32k

# configure the serial interface
PORT_LINUX ?= /dev/ttyUSB1

include $(RIOTBOARD)/common/esp32/Makefile.include
