## the cpu to build for
export CPU = stm32f3
export CPU_MODEL = stm32f303k8

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x10000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x4000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1ffff7ac

# load the common Makefile.include for Nucleo-32 boards
include $(RIOTBOARD)/nucleo32-common/Makefile.include
