BOARD ?= samr21-xpro
RIOTBASE ?= $(CURDIR)/../../..
include $(RIOTBASE)/tests/Makefile.tests_common

FEATURES_REQUIRED = periph_pwm

USEMODULE += xtimer
USEMODULE += shell

include $(RIOTBASE)/Makefile.include
