ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

# Provide stdio over USB by default
DEFAULT_MODULE += stdio_cdc_acm

# Use auto-initialization of usbus for stdio other USB
USEMODULE += auto_init_usbus

# This board requires support for Arduino bootloader.
FEATURES_REQUIRED += bootloader_arduino
USEMODULE += usb_board_reset

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
