# This board is based on an atmega CPU, thus import the features from it
include $(RIOTCPU)/atmega_common/Makefile.features

# Put defined MCU peripherals here (in alphabetical order)
# Peripherals are defined in cpu/atmega_common/Makefile.features
# Add only additional Peripherals

-include $(RIOTCPU)/atmega256rfr2/Makefile.features
