# This board is based on an ATmega CPU, thus import the features from it
include $(RIOTBOARD)/common/atmega/Makefile.features

# Put defined MCU peripherals here (in alphabetical order)
# Peripherals are defined in common/arduino-atmega/Makefile.features
# Add only additional Peripherals

-include $(RIOTCPU)/atmega256rfr2/Makefile.features
