# define the cpu used by Hamilton
export CPU = samd21
export CPU_MODEL = samr21e18a

# debugger config
export JLINK_DEVICE := atsamr21e18a
export TERMPROG := JLinkRTTClient
export OBJDUMPFLAGS += --disassemble --source --disassembler-options=force-thumb
export OFLAGS := -O binary --gap-fill 0xff

USEMODULE += rtt_stdio

include $(RIOTMAKE)/tools/jlink.inc.mk
