# debugger config
export JLINK_DEVICE := atsamr21e18a
OBJDUMPFLAGS += --disassemble --source --disassembler-options=force-thumb
OFLAGS := --gap-fill 0xff

# Configure Segger's RTT when stdio_rtt is loaded
ifneq (,$(filter stdio_rtt,$(USEMODULE)))
  TERMPROG = $(RIOTTOOLS)/jlink/jlink.sh
  TERMFLAGS = term-rtt
endif

include $(RIOTMAKE)/tools/jlink.inc.mk
