# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# this board has an on-board ST-link adapter
export DEBUG_ADAPTER ?= stlink

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
