APPLICATION = external_board
RIOTBASE ?= $(CURDIR)/../../

# Only support this board
#
# HACK I named the external board as 'native' to be in murdock test path for
# 'native'
# In practice it should be something else
BOARD = native

# Set without '?=' to also verify the docker integration when set with =
BOARDSDIR = $(CURDIR)/external_boards

include $(RIOTBASE)/Makefile.include
