# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB1
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# this board uses openocd with a custom reset command
OPENOCD_CMD_RESET_RUN =-c _reset
include $(RIOTMAKE)/tools/openocd.inc.mk

# use our own openocd script to flash since HiFive1 has reset problems.
FLASHER = $(RIOTBASE)/boards/hifive1/dist/flasher.sh
