# All stm32 families provide pm support
USEMODULE += pm_layered

# TODO fix no idle thread on stm32l5 (or more generally for cortex-m33)
ifeq (l5,$(CPU_FAM))
  USEMODULE += core_idle_thread
endif

# include stm32 common periph drivers, clock configurations and vectors
USEMODULE += periph stm32_clk stm32_vectors

ifneq (,$(filter periph_usbdev,$(FEATURES_USED)))
  USEMODULE += xtimer
endif

ifneq (,$(filter periph_uart_nonblocking,$(USEMODULE)))
  USEMODULE += tsrb
endif

ifneq (,$(filter stm32_eth,$(USEMODULE)))
  FEATURES_REQUIRED += periph_eth
  USEMODULE += netdev_eth
  USEMODULE += iolist
  USEMODULE += luid
  USEMODULE += xtimer
endif

ifneq (,$(filter periph_can,$(FEATURES_USED)))
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_gpio_irq
endif

include $(RIOTCPU)/cortexm_common/Makefile.dep
