# All stm32 families provide pm support
USEMODULE += pm_layered

# include stm32 common periph drivers, clock configurations and vectors
USEMODULE += periph stm32_clk stm32_vectors

ifneq (,$(filter periph_usbdev,$(FEATURES_USED)))
  USEMODULE += xtimer
endif

ifneq (STM32F030x4, $(CPU_LINE))
  # Retrieve vendor CMSIS headers from ST repository on GitHub
  # https://github.com/STMicroelectronics
  USEPKG += stm32cube
endif

include $(RIOTCPU)/cortexm_common/Makefile.dep
