# export this module and its includes
INCLUDES  += -I$(RIOTBOARD)/common/arduino-due/include

# setup flasher (using BOSSA)
BOSSA_VERSION = 1.8
BOSSA_ARDUINO_PREFLASH = yes
include $(RIOTMAKE)/tools/bossa.inc.mk
