## the cpu to build for
export CPU = stm32l0
export CPU_MODEL = stm32l073rz

export ROM_SIZE = 0x30000
export RAM_SIZE = 0x5000

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
