## the cpu to build for
export CPU = stm32l0
export CPU_MODEL = stm32l073rz

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x30000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x5000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1ff80050

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
