## the cpu to build for
export CPU = stm32l1
export CPU_MODEL = stm32l152ret6

export ROM_SIZE = 0x80000
export RAM_SIZE = 0x14000

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
