## the cpu to build for
export CPU = stm32l1
export CPU_MODEL = stm32l152ret6

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x80000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x14000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1ff800d0

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
