# when using miniterm set RTS and DTR lines to 0, otherwise the board is reset
MINITERMFLAGS = --rts 0 --dtr 0

include $(RIOTBOARD)/common/msba2/Makefile.include
include $(RIOTMAKE)/tools/openocd.inc.mk
