## the cpu to build for
export CPU = stm32f0
export CPU_MODEL = stm32f091rc

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x40000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x8000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1ffff7ac

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
