## the cpu to build for
export CPU = stm32f0
export CPU_MODEL = stm32f091rc

export ROM_SIZE = 0x40000
export RAM_SIZE = 0x8000

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
