ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += mma8x5x
endif

# include common nrf52840 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.nrf52840.dep

include $(RIOTBOARD)/common/nrf52/Makefile.dep
