# the cpu to build for
export CPU = stm32f3
export CPU_MODEL = stm32f302r8

export ROM_SIZE = 0x10000
export RAM_SIZE = 0x4000

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
