include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno nucleo-f031k6

USEMODULE += embunit
USEMODULE += json

TEST_ON_CI_WHITELIST += native

include $(RIOTBASE)/Makefile.include
