# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_rtt
FEATURES_PROVIDED += periph_timer

# Various other features (if any)
FEATURES_PROVIDED += netif

-include $(RIOTCPU)/nrf51/Makefile.features
