CPU = stm32f1
ifeq ($(STM32F103C8_FLASH_HACK),1)
  CPU_MODEL = stm32f103cb
else
  CPU_MODEL = stm32f103c8
endif

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart

# The board MPU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = cortex_m3_2
