ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += bmp280
  USEMODULE += si7021
endif

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += rail
endif

# include board common dependencies
include $(RIOTBOARD)/common/silabs/Makefile.dep

include $(RIOTCPU)/efm32/Makefile.dep
