## the cpu to build for
export CPU = stm32f7
export CPU_MODEL = stm32f746zg

export ROM_SIZE = 0x100000
export RAM_SIZE = 0x50000

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo144-common/Makefile.include
