FEATURES_PROVIDED += highlevel_stdio

include $(RIOTBOARD)/stm32f429i-disc1/Makefile.features

# stm32f429i-disco provides a custom default Kconfig clock configuration
KCONFIG_ADD_CONFIG += $(RIOTBOARD)/stm32f429i-disco/clock.config
