ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifeq (,$(filter nrfmin,$(USEMODULE)))
  ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
    USEPKG += nordic_softdevice_ble
  endif
endif
