PKG_NAME=ucglib
PKG_URL=https://github.com/basilfx/ucglib
PKG_VERSION=38d919a2bb817cd6b349829bd832af28caba098a
PKG_LICENSE=BSD-2-Clause

.PHONY: all

all: git-download
	"$(MAKE)" -C $(PKG_BUILDDIR)

include $(RIOTBASE)/pkg/pkg.mk
