INCLUDES += -I$(PKGDIRBASE)/ucglib/csrc

# The RIOT-OS interface needs this to store peripheral information.
CFLAGS += -DWITH_USER_PTR

# Link SDL if enabled.
ifneq (,$(filter ucglib_sdl,$(USEMODULE)))
  LINKFLAGS += `sdl2-config --libs`
endif
