ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

# Use Picolibc to reduce ROM usage
USEMODULE += picolibc

# limit the stack size so most tests and examples compile
CFLAGS += -DTHREAD_STACKSIZE_DEFAULT=512
