include ../Makefile.tests_common
RIOTBASE = /home/hskim/Desktop/rebase/RIOT-OS
BOARD_BLACKLIST := msb-430 msb-430h telosb wsn430-v1_3b wsn430-v1_4 z1

USEMODULE += fxos8700

include $(RIOTBASE)/Makefile.include
