## the cpu to build for
export CPU = stm32f0
export CPU_MODEL = stm32f031k6

export ROM_SIZE = 0x8000
export RAM_SIZE = 0x1000

# load the common Makefile.include for Nucleo-32 boards
include $(RIOTBOARD)/nucleo32-common/Makefile.include
