# define the cpu used by the msb-iot board
export CPU = stm32f4
export CPU_MODEL = stm32f415rg

#define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

export ROM_SIZE = 0x100000
export RAM_SIZE = 0x20000
export CCMRAM_SIZE = 0x10000

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
