## the cpu to build for
export CPU = stm32f3
export CPU_MODEL = stm32f303re

export ROM_SIZE = 0x800000
export RAM_SIZE = 0x10000

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
