APPLICATION = gnrc_mac_timeout
include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-leonardo \
                             arduino-mega2560 arduino-nano arduino-uno \
                             chronos i-nucleo-lrwan1 nucleo-f030r8 \
                             nucleo-f031k6 nucleo-f042k6 nucleo-l031k6 \
                             nucleo-l053r8 stm32f0discovery stm32l0538-disco \
                             stm32f030f4-demo waspmote-pro

USEMODULE += gnrc_mac

include $(RIOTBASE)/Makefile.include
