# Default auto-initialization of usbus for stdio other USB
USEMODULE += auto_init_usbus

# This boards requires support for Arduino bootloader.
USEMODULE += usb_board_reset
USEMODULE += stdio_cdc_acm

FEATURES_REQUIRED += bootloader_arduino
