include $(RIOTBOARD)/common/makefiles/stdio_cdc_acm.dep.mk

# use arduino-bootloader only if no other stdio_% other than stdio_cdc_acm
# is requested
ifneq (,$(filter stdio_cdc_acm,$(USEMODULE)))
  USEMODULE += boards_common_samd21-arduino-bootloader
  USEMODULE += usb_board_reset
endif
