# Provide stdio over USB by default
DEFAULT_MODULE += stdio_cdc_acm

# Default auto-initialization of usbus for stdio other USB
DEFAULT_MODULE += auto_init_usbus

# This boards requires support for Arduino bootloader.
USEMODULE += arduino_bootloader
USEMODULE += boards_common_samd21-arduino-bootloader
