BOARD_INSUFFICIENT_MEMORY := \
    blackpill \
    calliope-mini \
    i-nucleo-lrwan1 \
    nucleo-f030r8 \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-f072rb \
    nucleo-f303k8 \
    nucleo-l053r8 \
    opencm904 \
    saml10-xpro \
    saml11-xpro \
    spark-core \
    stm32f030f4-demo \
    #
