PKG_NAME=emlearn
PKG_URL=https://github.com/emlearn/emlearn
PKG_VERSION=0.10.1
PKG_LICENSE=MIT

.PHONY: all

all:
	"$(MAKE)" -C $(PKG_BUILDDIR) -f $(CURDIR)/Makefile.$(PKG_NAME)

include $(RIOTBASE)/pkg/pkg.mk
