APPLICATION = driver_tps6274x
include ../Makefile.tests_common

# Known boards with support for the TPS6274x
BOARD_WHITELIST = jiminy-mega256rfr2

FEATURES_REQUIRED = periph_gpio

USEMODULE += tps6274x
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
