# define the cpu used by the nucleo-f412 board
export CPU = stm32f4
export CPU_MODEL = stm32f412zg

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x100000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x40000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1fff7a10

# load the common Makefile.include for Nucleo-144 boards
include $(RIOTBOARD)/nucleo144-common/Makefile.include
