# define the cpu used by the nucleo-f412 board
export CPU = stm32f4
export CPU_MODEL = stm32f412zg

export ROM_SIZE = 0x100000
export RAM_SIZE = 0x40000

# load the common Makefile.include for Nucleo-144 boards
include $(RIOTBOARD)/nucleo144-common/Makefile.include
