APPLICATION = openwsn_eui64

BOARD ?= iotlab_m3

include ../Makefile.tests_common

USEPKG += openwsn
USEMODULE += openwsn_openstack
USEMODULE += openwsn_scheduler

include $(RIOTBASE)/Makefile.include
