# we use shared STM32 configuration snippets
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# set the default id
DFU_ID = 0483:df11

# Set ALT to 0
DFU_ALT = 0

include $(RIOTMAKE)/tools/dfu.inc.mk

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk
