## the cpu to build for
export CPU = stm32l1
export CPU_MODEL = stm32l151rc

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# set the default id
DFU_ID ?= 0483:df11

# this board is flashed using DFU
DFU_ARGS += -d $(DFU_ID) -a 0 -s 0x08000000:leave
include $(RIOTMAKE)/tools/dfu.inc.mk

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk
