INCLUDES += -I$(PKGDIRBASE)/EDHOC-C/include \
            -I$(PKGDIRBASE)/EDHOC-C/src \
            -I$(RIOTBASE)/pkg/edhoc-c/include \
            #

ifneq (,$(filter edhoc-c_crypto_wolfssl,$(USEMODULE)))
  CFLAGS += -DHAVE_AESCCM
  CFLAGS += -DHAVE_HKDF
endif

# EDHOC-C configuration file for RIOT
CFLAGS += -DEDHOC_CONFIG_FILE=\"edhoc_config.h\"
CFLAGS += -DEMPTY_X509
