ifneq (,$(filter stdio_uart,$(USEMODULE)))
  FEATURES_REQUIRED += periph_lpuart
endif
ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += sx1261
  USEMODULE += sx126x_stm32wl
endif
include $(RIOTBOARD)/common/nucleo/Makefile.dep
