# define the cpu used by the nucleo-f411 board
export CPU = stm32f4
export CPU_MODEL = stm32f411re

export ROM_SIZE = 0x80000
export RAM_SIZE = 0x20000

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
