ifneq (,$(filter cc26x2_cc13x2_prop_rf,$(USEMODULE)))
  USEMODULE += cc26x2_cc13x2_prop_rf
  USEMODULE += cc26x2_cc13x2_rfc
  USEPKG += cc26xx_cc13xx_driverlib
  USEMODULE += cc13x2_cc26x2_driverlib
endif

include ${RIOTCPU}/cc26xx_cc13xx/Makefile.dep
