include ../Makefile.tests_common

USEMODULE += shell
USEMODULE += can
USEMODULE += isrpipe

# specify the CAN driver you want to use here by including its module.
# the test app will adapt itself to the used module.
USEMODULE += mcp2515

include $(RIOTBASE)/Makefile.include
