## the cpu to build for
export CPU = stm32l4
export CPU_MODEL = stm32l476rg

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x100000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x20000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1fff7590

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
