RIOTBASE ?= $(CURDIR)/../../..
include $(RIOTBASE)/tests/Makefile.tests_common

# include and auto-initialize all available sensors
USEMODULE += saul_default

USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
