INCLUDES += -I$(RIOTBOARD)/common/silabs/include
INCLUDES += -I$(RIOTBOARD)/common/silabs/drivers/include

PROGRAMMER ?= jlink

# Silabs boards can use openocd or jlink programmers
PROGRAMMERS_SUPPORTED ?= jlink openocd

JLINK_DEVICE ?= ${CPU_MODEL}
OPENOCD_CONFIG ?= board/efm32.cfg
