# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_dac
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += backup_ram

-include $(RIOTCPU)/arm7_common/Makefile.features
