# include module specific includes
INCLUDES += -I$(RIOTCPU)/cortexm_common/include
INCLUDES += -I$(RIOTCPU)/cortexm_common/include/vendor

USEMODULE += cortexm_common_periph
USEMODULE += periph_pm_cortexm

export IMAGE_HDR_SIZE ?= 512
