USEMODULE += tinydtls

USEMODULE += memarray
USEMODULE += hashes
USEMODULE += tinydtls_aes
USEMODULE += tinydtls_ecc
USEMODULE += random

# tinydtls needs cryptographically secure randomness
ifeq (,$(filter prng_%,$(USEMODULE)))
  USEMODULE += prng_sha1prng
endif

# TinyDTLS only has support for 32-bit architectures ATM
FEATURES_REQUIRED += arch_32bit
