# the cpu to build for
export CPU = stm32l4
export CPU_MODEL = stm32l475vg

# configure the serial terminal
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))
include $(RIOTMAKE)/tools/serial.inc.mk

# this board uses st-link
export DEBUG_ADAPTER ?= stlink
export STLINK_VERSION ?= 2-1

# include openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
