include ../Makefile.tests_common

USEMODULE += ztimer ztimer_periph ztimer_usec #ztimer_msec
#USEMODULE += ztimer_rtt
USEMODULE += ztimer_convert_frac

TEST_ON_CI_WHITELIST += all

include $(RIOTBASE)/Makefile.include
