include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno

USEMODULE += heap_cmd
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

TEST_ON_CI_WHITELIST += all

include $(RIOTBASE)/Makefile.include
