## the cpu to build for
export CPU = stm32f1
export CPU_MODEL = stm32f103c8

include $(RIOTBOARD)/common/blxxxpill/Makefile.include
export OPENOCD_CONFIG = $(RIOTBOARD)/common/blxxxpill/dist/openocd.cfg

USEMODULE += boards_common_blxxxpill
