# If application does not provide the CFLAGS
ifeq (,$(filter -DUSB_CONFIG_VID=% -DUSB_CONFIG_VID=%,$(CFLAGS)))
  # http://pid.codes/1209/7D00/
  USB_CONFIG_VID ?= 0x1209
  USB_CONFIG_PID ?= 0x7D00

  CFLAGS += -DUSB_CONFIG_VID=$(USB_CONFIG_VID) -DUSB_CONFIG_PID=$(USB_CONFIG_PID)
endif

include $(RIOTBOARD)/common/nrf52/Makefile.include
