ifeq (,$(filter stdio_%,$(USEMODULE)))
  USEMODULE += stdio_rtt
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
