ifeq (,$(filter stdio_%,$(USEMODULE)))
  ifeq (,$(filter auto_init,$(DISABLE_MODULE)))
    USEMODULE += auto_init_usbus
    USEMODULE += stdio_cdc_acm
  else
    # Can't initialize USB due to missing auto_init
    USEMODULE += stdio_rtt
  endif
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
