BOARD ?= samr21-xpro

RIOTBASE ?= $(CURDIR)/../../..
include $(RIOTBASE)/tests/Makefile.tests_common

FEATURES_REQUIRED += cpu_check_address

USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include
