INCLUDES += -I$(RIOTBASE)/pkg/semtech-loramac/include \
            -I$(PKGDIRBASE)/semtech-loramac/src/mac \
            -I$(PKGDIRBASE)/semtech-loramac/src/boards/mcu/stm32 \
            -I$(PKGDIRBASE)/semtech-loramac/src/system/crypto \
            -I$(PKGDIRBASE)/semtech-loramac/src

CFLAGS += -Wno-missing-field-initializers -Wno-unused-parameter -Wno-sign-compare

DIRS += $(RIOTBASE)/pkg/semtech-loramac/contrib
