## the cpu to build for
export CPU = stm32f7
export CPU_MODEL = stm32f767zi

export ROM_SIZE = 0x200000
export RAM_SIZE = 0x80000

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo144-common/Makefile.include
