BOARD ?= calliope-mini
RIOTBASE ?= $(CURDIR)/../../..
include $(RIOTBASE)/tests/Makefile.tests_common

# This test application is for the Calliope mini only
BOARD_WHITELIST := calliope-mini

# We want to test the Calliope mini support module
USEMODULE += mini

include $(RIOTBASE)/Makefile.include
