include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-leonardo arduino-nano \
                             arduino-uno nucleo-f031k6

USEPKG += talking_leds
USEMODULE += arduino_lib

include $(RIOTBASE)/Makefile.include
