# define the cpu used by SODAQ Autonomo board
export CPU = samd21
export CPU_MODEL = samd21j18a

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x40000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x8000

include $(RIOTMAKE)/boards/sam0.inc.mk
