# we use shared STM32 configuration snippets
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# this board has an on-board ST-link adapter
DEBUG_ADAPTER ?= stlink

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
