# define the cpu used by Arduino/Genuino Zero board
export CPU = samd21
export CPU_MODEL = samd21g18a

export ROM_SIZE = 0x40000
export RAM_SIZE = 0x8000

# set edbg device type
EDBG_DEVICE_TYPE = atmel_cm0p

include $(RIOTMAKE)/boards/sam0.inc.mk
