include ../Makefile.tests_common

FEATURES_REQUIRED += periph_dac
FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_timer_periodic

BLOBS += hello.raw

USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
