## the cpu to build for
export CPU = stm32l0
export CPU_MODEL = stm32l031k6

LINKFLAGS += $(LINKFLAGPREFIX)--defsym=rom_length=0x8000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=ram_length=0x2000
LINKFLAGS += $(LINKFLAGPREFIX)--defsym=cpu_id_address=0x1ff80050

# load the common Makefile.include for Nucleo-32 boards
include $(RIOTBOARD)/nucleo32-common/Makefile.include
