USEMODULE += random
USEPKG += qDSA

# qDSA on AVR needs slightly larger-than-default stack
ifneq (atmega_common,$(USEMODULE))
  CFLAGS += -DTHREAD_STACKSIZE_MAIN=\(2*THREAD_STACKSIZE_DEFAULT+THREAD_EXTRA_STACKSIZE_PRINTF\)
endif
